In [1]:
import tensorflow as tf

In [2]:
value = tf.constant([
    [1., 2., 3.],
    [4., 5., 6.]
])
print(f"""
value: {value}
shape: {value.shape}
type: {value.dtype}
""")


value: [[1. 2. 3.]
 [4. 5. 6.]]
shape: (2, 3)
type: <dtype: 'float32'>



In [3]:
print(value + value)

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


In [4]:
print(value * 5)

tf.Tensor(
[[ 5. 10. 15.]
 [20. 25. 30.]], shape=(2, 3), dtype=float32)


In [5]:
print(value @ tf.transpose(value))

tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [6]:
print(tf.concat([value, value, value], axis=0))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]], shape=(6, 3), dtype=float32)


In [7]:
print(tf.nn.softmax(value))

tf.Tensor(
[[0.09003057 0.24472848 0.6652409 ]
 [0.09003057 0.24472848 0.6652409 ]], shape=(2, 3), dtype=float32)


In [8]:
print(tf.reduce_sum(value, axis=-1))

tf.Tensor([ 6. 15.], shape=(2,), dtype=float32)


In [9]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]